c3p5RazorMovie/Pages/Movies/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using DataModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace c3p5RazorMovie.Pages.Movies
{
    public class CreateModel : PageModel
    {
        private readonly DataModels.dbContext _context;
        private readonly IWebHostEnvironment _hostingEnvir;

        public CreateModel(DataModels.dbContext context, IWebHostEnvironment hostingEnvir)
        {
            _context = context;
            _hostingEnvir = hostingEnvir;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Movie Movie { get; set; }
        public string ErrorMessage { get; set; }


        public async Task<IActionResult> OnPostAsync()
        {
            var formSecurity = Request.Form["SecurityText"].ToString();
            var sessionSecurity = HttpContext.Session.GetString("SecurityText");


            if (formSecurity != sessionSecurity)
            {

                ErrorMessage = "(시크릿트 문자를 확인하세요)";
                return Page();
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var CreateMovie = new Movie();

            if (await TryUpdateModelAsync<Movie>(
                CreateMovie, "movie",
                m => m.Title, m => m.ReleaseDate, m => m.Gener, m => m.Price))

            {
                _context.Movies.Add(CreateMovie);
                await _context.SaveChangesAsync();


                await OnPostUploadAsync(CreateMovie.ID);
                return RedirectToPage("./Index");

            }
            
            return Page();
        }


        public async Task<IActionResult> OnPostAjaxArticleAsync()
        {
            var formSecurity = Request.Form["SecurityText"].ToString();
            var sessionSecurity = HttpContext.Session.GetString("SecurityText");


            if (formSecurity != sessionSecurity)
            {

                ErrorMessage = "(시크릿트 문자를 확인하세요)";
                return Page();
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            var CreateMovie = new Movie();

            if (await TryUpdateModelAsync<Movie>(
                CreateMovie, "movie",
                m => m.Title, m => m.ReleaseDate, m => m.Gener, m => m.Price))

            {
                _context.Movies.Add(CreateMovie);
                await _context.SaveChangesAsync();

                return new OkObjectResult(CreateMovie.ID);
                
            }

            return Page();
        }

        public async Task<IActionResult> OnPostUploadAsync(int Id)
        {
            string[] pathSplit;
            var ajax_file = Request.Form.Files;  //(매개변수로 받음)

            string path_for_Uploaded_Files = _hostingEnvir.WebRootPath + "\\UserFiles\\";

            foreach (var uploaded_file in ajax_file)
            {

                pathSplit = uploaded_file.FileName.Split('\\');
                string uploaded_Filename = pathSplit[pathSplit.Length - 1];
                string new_Filename_on_Server = path_for_Uploaded_Files + "\\" + uploaded_Filename;



                FileInfo finfo = new FileInfo(new_Filename_on_Server);

                if (finfo.Exists)
                {
                    int fIndex = 0;
                    string fExtension = finfo.Extension;
                    string fRealName = uploaded_Filename.Replace(fExtension, "");
                    do
                    {
                        fIndex++;
                        uploaded_Filename = fRealName + "_" + fIndex.ToString() + fExtension;
                        finfo = new FileInfo(Path.Combine(path_for_Uploaded_Files, uploaded_Filename));
                    } while (finfo.Exists);

                    new_Filename_on_Server = System.IO.Path.Combine(
                        path_for_Uploaded_Files, uploaded_Filename);

                }


                using (FileStream stream = new FileStream(new_Filename_on_Server, FileMode.Create))
                {
                    await uploaded_file.CopyToAsync(stream);
                }


                if (Id > 0)
                {
                    _context.AttachFiles.Add(new AttachFile
                    {
                        MovieID = Id,
                        FileName = uploaded_Filename
                    });

                    await _context.SaveChangesAsync();

                }
                
            }

            return Page();
            
        }

       
    }
}

c3p5RazorMovie/Pages/Movies/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataModels;

namespace c3p5RazorMovie.Pages.Movies
{
    public class DeleteModel : PageModel
    {
        private readonly DataModels.dbContext _context;

        public DeleteModel(DataModels.dbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Movie Movie { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _context.Movies.FirstOrDefaultAsync(m => m.ID == id);

            if (Movie == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _context.Movies.FindAsync(id);

            if (Movie != null)
            {
                _context.Movies.Remove(Movie);
                await _context.SaveChangesAsync();
            }

            return Redirect("./Index" + Request.Query["Path"].ToString());
        }
    }
}

c3p5RazorMovie/Pages/Movies/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataModels;

namespace c3p5RazorMovie.Pages.Movies
{
    public class DetailsModel : PageModel
    {
        private readonly DataModels.dbContext _context;

        public DetailsModel(DataModels.dbContext context)
        {
            _context = context;
        }

        public Movie Movie { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _context.Movies.FirstOrDefaultAsync(m => m.ID == id);

            if (Movie == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

c3p5RazorMovie/Pages/Movies/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using DataModels;
using Microsoft.AspNetCore.Http;

namespace c3p5RazorMovie.Pages.Movies
{
    public class EditModel : PageModel
    {
        private readonly DataModels.dbContext _context;

        public EditModel(DataModels.dbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Movie Movie { get; set; }
        public string ErrorMessage { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Movie = await _context.Movies.FirstOrDefaultAsync(m => m.ID == id);

            if (Movie == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            var formSecurity = Request.Form["SecurityText"].ToString();
            var sessionSecurity = HttpContext.Session.GetString("SecurityText");


            if (formSecurity != sessionSecurity)
            {

                ErrorMessage = "(시크릿트 문자를 확인하세요)";
                return Page();
            }
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var MovieToUpdate = await _context.Movies.FindAsync(id);


            if (await TryUpdateModelAsync<Movie>(
                MovieToUpdate, "movie",
                m => m.Title, m => m.ReleaseDate, m => m.Gener, m => m.Price))
            {
                await _context.SaveChangesAsync();
                return Redirect("./Index" + Request.Query["Path"].ToString());

            }

            return Page();

        }

        private bool MovieExists(int id)
        {
            return _context.Movies.Any(e => e.ID == id);
        }
    }
}

c3p5RazorMovie/Pages/Movies/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using DataModels;

namespace c3p5RazorMovie.Pages.Movies
{
    public class IndexModel : PageModel
    {
        private readonly DataModels.dbContext _context;

        public IndexModel(DataModels.dbContext context)
        {
            _context = context;
        }

        public IList<Movie> Movie { get;set; }
        
        #region Searching, Paging 변수
        public SearchingVar searchingVar { get; set; }


        public int TotalCount { get; set; }
        public int PageIndex { get; set; }

        #endregion



        public async Task OnGetAsync()
        {
            ///// Paging 변수 초기화

            int pageIndex = 0;
            int pageSize = 3;


            ////////  Searching 변수 초기화  ///////////////////////////////////////////////////////////////////////////

            string searchField = string.Empty;
            string searchQuery = string.Empty;
            bool searchMode = false;

            if (!String.IsNullOrEmpty(Request.Query["SearchField"]) &&
                 !String.IsNullOrEmpty(Request.Query["SearchQuery"]))
            {
                searchMode = true;
                searchField = Request.Query["SearchField"];
                searchQuery = Request.Query["SearchQuery"];

            }

            searchingVar = new SearchingVar();
            searchingVar.SearchMode = searchMode;
            searchingVar.SearchField = searchField;
            searchingVar.SearchQuery = searchQuery;
            searchingVar.DicField = new Dictionary<string, string>()
            {
                { "Title", "제목" },
                { "Genee", "장르" }
            };

            //////////////////////////////////////////////////////////////////////////////

            var iMovie = (IQueryable<Movie>)_context.Movies.Include(m => m.AttachFiles).AsNoTracking();
            

            if (searchMode)
            {
                switch (searchField)
                {
                    case "Title":
                        iMovie = iMovie.Where(s => s.Title.Contains(searchQuery));
                        break;

                    case "Gener":
                        iMovie = iMovie.Where(s => s.Gener.Contains(searchQuery));
                        break;

                    default:
                        iMovie = iMovie.Where(s => s.Title.Contains(searchQuery));
                        break;
                }

            }


            iMovie = iMovie.OrderByDescending(s => s.ID);



            //[1] 쿼리스트링에 따른 페이지 보여주기
            if (!string.IsNullOrEmpty(Request.Query["Page"]))
            {
                // Page는 보여지는 쪽은 1, 2, 3, ... 코드단에서는 0, 1, 2, ...
                pageIndex = Convert.ToInt32(Request.Query["Page"]) - 1;
                //Response.Cookies.Append("Page", pageIndex.ToString());
            }

            TotalCount = iMovie.Count();
            PageIndex = pageIndex + 1;

            Movie = await iMovie
                .Skip((pageIndex) * pageSize).Take(pageSize).ToListAsync();
        }
    }
}

c3p5RazorMovie/ViewComponents/MovieFormViewComponent.cs
using DataModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace c3p5RazorMovie.ViewComponents
{
    public class MovieFormViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(MovieForm frm)
        {
            return View(frm);
        }

    }
}

c3p5RazorMovie/ViewComponents/SearchingViewComponent.cs
using DataModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace c3p5RazorMovie.ViewComponents
{
    public class SearchingViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(SearchingVar searchingVar)
        {
            return View(searchingVar);
        }
    }
}

c3p5RazorMovie/Pages/Movies/Create.cshtml
@page
@model c3p5RazorMovie.Pages.Movies.CreateModel

@{

    var movieForm = new DataModels.MovieForm();

    movieForm.Movie = Model.Movie;
    movieForm.ErrorMessage = Model.ErrorMessage;   //보안문자를 사용 안하면 필요없음
    movieForm.FrmType = DataModels.FrmType.Write;
    movieForm.ReturnUrl = Request.Query["Path"].ToString();


    ViewData["Title"] = DataModels.FrmTypeExtensions.ToFriendlyString(movieForm.FrmType);

}


<h2>
    Movies &nbsp;&nbsp;
    <small><i class="glyphicon glyphicon-hand-right"></i> @DataModels.FrmTypeExtensions.ToFriendlyString(movieForm.FrmType) 입니다.</small>
</h2>
<hr />

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-8">
        @await Component.InvokeAsync("MovieForm", movieForm)
    </div>
</div>

@section stylesheets {
    <link href="~/css/UploadCtrl.css" rel="stylesheet" />

}

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/UploadCtrl.js"></script>

}

c3p5RazorMovie/Pages/Movies/Delete.cshtml
@page
@model c3p5RazorMovie.Pages.Movies.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Gener)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Gener)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Price)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Movie.ID" />

        <div class="btn-group" role="group" aria-label="Basic example">
            <input type="submit" value="삭제" class="btn btn-outline-danger" />
            <a href='./Index@(Request.Query["Path"].ToString())' class="btn btn-outline-secondary">목록</a>

        </div>

    </form>
</div>

c3p5RazorMovie/Pages/Movies/Details.cshtml
@page
@model c3p5RazorMovie.Pages.Movies.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.ReleaseDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.ReleaseDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Gener)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Gener)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Movie.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Movie.Price)
        </dd>
    </dl>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
    <a asp-page="./Edit" asp-route-id="@Model.Movie.ID" asp-route-path="@(Request.Query["Path"].ToString())" class="btn btn-outline-primary">수정</a>
    <a asp-page="./Delete" asp-route-id="@Model.Movie.ID" asp-route-path="@(Request.Query["Path"].ToString())" class="btn btn-outline-danger">삭제</a>
    <a href='./Index@(Request.Query["Path"].ToString())' class="btn btn-outline-secondary">목록</a>

</div>

c3p5RazorMovie/Pages/Movies/Edit.cshtml
@page
@model c3p5RazorMovie.Pages.Movies.EditModel

@{

    var movieForm = new DataModels.MovieForm();

    movieForm.Movie = Model.Movie;
    movieForm.ErrorMessage = Model.ErrorMessage;   //보안문자를 사용 안하면 필요없음
    movieForm.FrmType = DataModels.FrmType.Modify;
    movieForm.ReturnUrl = Request.Query["Path"].ToString();


    ViewData["Title"] = DataModels.FrmTypeExtensions.ToFriendlyString(movieForm.FrmType);

}


<h2>
    Movies &nbsp;&nbsp;
    <small><i class="glyphicon glyphicon-hand-right"></i> @DataModels.FrmTypeExtensions.ToFriendlyString(movieForm.FrmType) 입니다.</small>
</h2>
<hr />

<div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-8">
        @await Component.InvokeAsync("MovieForm", movieForm)
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

c3p5RazorMovie/Pages/Movies/Index.cshtml
@page
@model c3p5RazorMovie.Pages.Movies.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>
    Movies &nbsp;&nbsp;
    <small><i class="glyphicon glyphicon-hand-right"></i> 영화목록 입니다.</small>
</h2>
<hr />


@*검색상자*@
<div class="row" style="margin-bottom:10px">
    <div class="col-4">

        <a asp-page="Create" asp-route-path="@HttpContext.Request.QueryString" class="btn btn-outline-danger">Create New</a>

    </div>
    <div class="col-4">


    </div>
    <div class="col-4 text-right">
        @await Component.InvokeAsync("Searching", Model.searchingVar)
    </div>
</div>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Movie[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie[0].ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie[0].Gener)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Movie[0].Price)
            </th>
            <th>
                포스트
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.Movie)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Gener)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @foreach (var fn in item.AttachFiles)
                {
                    @Html.DisplayFor(modelItem => fn.FileName) <br />

                }

            </td>
           
            <td>
                <a asp-page="./Edit" asp-route-id="@item.ID" asp-route-path="@HttpContext.Request.QueryString">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.ID" asp-route-path="@HttpContext.Request.QueryString">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.ID" asp-route-path="@HttpContext.Request.QueryString">Delete</a>

            
            </td>
        </tr>
        }
    </tbody>
</table>


@*페이징*@
<hr />

<div class="text-center">
    <paging4 url="@HttpContext.Request.Path"
             page-index="@Model.PageIndex"
             page-size=3
             page-etc=''
             record-count=@Model.TotalCount
             page-counter=5
             search-mode='@Model.searchingVar.SearchMode'
             search-field='@Model.searchingVar.SearchField'
             search-query='@Model.searchingVar.SearchQuery'>
    </paging4>
</div>


@section stylesheets {
    @*font-awasome 설정 cdn*@
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
}